{
  "ports": {
    "of:0000000000000001/1": {
      "interfaces": [
        {
          "name": "vethbr1r12",
          "ips": [
            "192.168.63.1",
            "fd32::1"
          ]
        }
      ]
    },
    "of:0000aebcb8ad0c45/3": {
      "interfaces": [
        {
          "name": "vethbr1r12",
          "ips": [
            "192.168.70.53",
            "fd70::53"
          ]
        }
      ]
    }
  },
  "nycu.winlab.vRouter": {
    "router": {
      "vrrouting": "of:0000000000000001/1",
      "vrrouting-mac": "00:00:00:00:00:01",
      "gateway-ip4": "172.16.53.69",
      "gateway-ip6": "2a0b:4e07:c4:53::69",
      "v4-peers": [
        "192.168.70.1", "1923168.70.253",
        "192.168.63.1", "192.168.63.2"
      ],
      "v6-peers": [
        "fd70::1", "fd70::253",
        "fd32::1", "fd32::2"
      ]
    }
  }
}